version: '3.8'

services:
  mysql:
    image: 'mysql:5.6.27'
    ports:
      - "3306:3306"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MYSQL_DATABASE: book
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - redis_data:/data

  fidibo:
    build:
      context: .
      dockerfile: ./dockerfile
    restart: always
    ports:
      - "8888:8888"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - mysql
      - redis
    environment:
      InternalNetwork: "true"

volumes:
  mysql_data:
  redis_data: