version: '3.8'

services:
  mysql:
    image: 'mysql:5.6.27'
    container_name: 'fidibo-mysql'
    ports:
      - "3306:3306"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MYSQL_DATABASE: book
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: 'redis:latest'
    container_name: 'fidibo-redis'
    ports:
      - "6379:6379"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: